import json
from datetime import datetime
from pathlib import Path

STORAGE_PATH = Path("storage/reports")


def generate_report(student_name, session_data):
    """
    session_data = {
        "topics_studied": ["Decimals", "Fractions"],
        "hard_topics": ["Decimals"],
        "teaching_style_worked": "analogy",
        "due_reviews": ["Fractions"],
        "independence_score": 65.5,
        "struggle_level": "Moderate Struggle",
        "total_questions": 10,
        "correct_first_attempt": 6
    }
    """

    STORAGE_PATH.mkdir(parents=True, exist_ok=True)

    today = datetime.now().strftime("%Y-%m-%d")
    time_now = datetime.now().strftime("%I:%M %p")
    filename = STORAGE_PATH / f"{student_name}_{today}.html"

    topics_studied_html = "".join(f"<li>{t}</li>" for t in session_data.get("topics_studied", []))
    hard_topics_html = "".join(f"<li>{t}</li>" for t in session_data.get("hard_topics", []))
    due_reviews_html = "".join(f"<li>{t}</li>" for t in session_data.get("due_reviews", []))

    style_map = {
        "analogy": "Analogies and real-world comparisons",
        "step_by_step": "Step by step explanations",
        "real_world_story": "Real world stories",
        "counter_example": "Counter examples and challenges",
    }
    teaching_style = style_map.get(session_data.get("teaching_style_worked", "analogy"), "Analogies")

    score = session_data.get("independence_score", 0)
    struggle = session_data.get("struggle_level", "Normal")
    total_q = session_data.get("total_questions", 0)
    correct = session_data.get("correct_first_attempt", 0)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LEYUM Report - {student_name} - {today}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background: #f9f9f9;
            color: #333;
        }}
        h1 {{
            color: #2c7be5;
            font-size: 24px;
        }}
        h2 {{
            color: #444;
            font-size: 18px;
            border-bottom: 2px solid #2c7be5;
            padding-bottom: 5px;
        }}
        .card {{
            background: white;
            border-radius: 12px;
            padding: 16px;
            margin-bottom: 16px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.08);
        }}
        .score {{
            font-size: 48px;
            font-weight: bold;
            color: #2c7be5;
            text-align: center;
        }}
        ul {{
            padding-left: 20px;
            line-height: 1.8;
        }}
        .footer {{
            text-align: center;
            color: #999;
            font-size: 12px;
            margin-top: 30px;
        }}
        .highlight {{
            background: #e8f4ff;
            border-left: 4px solid #2c7be5;
            padding: 10px 14px;
            border-radius: 6px;
            margin-top: 10px;
        }}
    </style>
</head>
<body>

    <h1>📘 LEYUM Session Report</h1>
    <p><strong>Student:</strong> {student_name}<br>
    <strong>Date:</strong> {today} &nbsp;|&nbsp; <strong>Time:</strong> {time_now}</p>

    <div class="card">
        <h2>📊 Independence Score</h2>
        <div class="score">{score}%</div>
        <p style="text-align:center">Questions answered correctly on first attempt: <strong>{correct} / {total_q}</strong></p>
    </div>

    <div class="card">
        <h2>📚 Topics Studied Today</h2>
        <ul>{topics_studied_html}</ul>
    </div>

    <div class="card">
        <h2>⚠️ Topics That Were Hard</h2>
        <ul>{hard_topics_html if hard_topics_html else "<li>None - great session!</li>"}</ul>
    </div>

    <div class="card">
        <h2>✅ What Worked Best</h2>
        <div class="highlight">
            {student_name} responded best to: <strong>{teaching_style}</strong>
        </div>
    </div>

    <div class="card">
        <h2>🔁 Review Tomorrow</h2>
        <ul>{due_reviews_html if due_reviews_html else "<li>Nothing due - check back tomorrow!</li>"}</ul>
    </div>

    <div class="card">
        <h2>🧠 Struggle Level This Session</h2>
        <p><strong>{struggle}</strong></p>
    </div>

    <div class="footer">
        Generated by LEYUM - Offline AI Tutor - No internet required<br>
        All data stays on this device only.
    </div>

</body>
</html>"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    return str(filename)
